# Generated by Django 3.2.10 on 2022-09-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('user_id', models.CharField(max_length=34, primary_key=True, serialize=False)),
                ('x_open', models.SmallIntegerField(default=0)),
                ('y_open', models.SmallIntegerField(default=0)),
                ('z_open', models.SmallIntegerField(default=0)),
                ('x_close', models.SmallIntegerField(default=0)),
                ('y_close', models.SmallIntegerField(default=0)),
                ('z_close', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
